# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version && sudo apt-get install rsync

      - add_ssh_keys:
          fingerprints:
            - "d0:68:f4:12:a1:92:5f:e8:67:20:17:0c:2c:d8:c8:77"

      - checkout
      # - restore_cache:
      #    keys:
      #     - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     - deps9-{{ .Branch }}
      #     - deps9
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"

      - run: ssh-keyscan -H 23.239.23.178 >> ~/.ssh/known_hosts
      # - run: rsync -avce ssh . root@23.239.23.178:/opt/owlapi/
      - run: ssh root@23.239.23.178 "cd /opt/OwlAPI && git pull && pipenv install && sudo service OwlAPI restart"
