# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test
jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d0:68:f4:12:a1:92:5f:e8:67:20:17:0c:2c:d8:c8:77"
      - run: ssh-keyscan -H 23.239.23.178 >> ~/.ssh/known_hosts
      # TODO: make this more robust
      - run: ssh root@23.239.23.178 "cd /opt/OwlAPI && git checkout . && git pull && pipenv install && sudo service OwlAPI restart"
  test:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
         keys:
          - deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - deps-v1-{{ .Branch }}-
          - deps-v1-
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pipenv run python -m pytest tests --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
